### ISSUE TITLE
Execute middlewares before executing endpoint's method

### ISSUE THREAD

**Issue by toksdotdev** [rudolfsonjunior/express-routes-mapper#20]
I feel it would be awesome if we could execute a middleware before entering a specific endpoint method in a controller. I know there are work around this, but this should be easily available.

e.g. something of this fashion:
```Javascript
app.post('/user', [ validate_some_stuffs(...) ], (req, res) => {  // validation middle-ware executes first

});
```

**Comment by aichbauer** [comment]
That would be a awesome feature 👍 

Any idea on how we could structure these middleware? I am open for ideas 😀

**Comment by toksdotdev** [comment]
Having thought about this, I feel **for backward compatibility**, we could check:

-  **If** the value of `'GET /user:id'` which is (`'UserController.get'`) is of type `String`, take the value as the controller and method
i.e.   `'GET /user:id': 'UserController.get'`

- **Else** use the new method we want to adopt below:
> **Note** each middleware would receive both the `request`, `response` object and *optionally* a `next` callback

```Javascript
const routes = {
  'POST /user': 'UserController.create', // this old style still supported

  'GET /user:id': {
    path: 'UserController.get',
    middlewares: [
      // An array of middle wares could be specified 
      // without the open & closing brackets i.e. ()

      // e.g. 
      // 
      // checkIfAuthenticated   ----> correct
      // checkIfAuthenticated() ----> wrong   

      // The later is wrong because the middle-ware would be triggered
      // on `const routes` initialization, instead of before the controller
      // method execution and would prevent the middleware from accessing the 
      // `request` and `response` params that could be passed.
      // 
    ]
  },
};

export default routes;
```

**Middle-wares would be executed in descending order for simplicity.**

**Final example**

``` Javascript
const routes = {
  'GET /user:id': {
    path: 'UserController.get',
    middlewares: [
         checkIfAutheticated,
         verifyFacebookAuth,  // this would come in handy for passport authentication
    ],
    
  'POST /user': 'UserController.create'
  },
};
```

Please feel free to correct me were I might be wrong...

**Comment by toksdotdev** [comment]
This middleware execution could be executed right before this code clock below is called, with some slight modifications.

 https://github.com/aichbauer/express-routes-mapper/blob/a190d079ad3342bd5658e5e2fc8efdad07166d30/src/index.js#L49-L57

I could send in a PR if you deem this feature fit...

**Comment by aichbauer** [comment]
Hey @TNkemdilim,

this sounds great. Send a PR and we can see if there is something we can improve...

**Comment by toksdotdev** [comment]
Gotcha!!!

**Comment by toksdotdev** [comment]
Sorry, should send in a PR shortly,  as I've been quite busy.

**Comment by aichbauer** [comment]
@TNkemdilim is there any update on this issue? I really like the idea of executing middleware before a specific route.

**Comment by joneldiablo** [comment]
Hi! I have this code:
```
app.use('/public', mapRoutes(config.publicRoutes, './controllers/'));
app.use('/private', config.verifyToken, mapRoutes(config.privateRoutes, './controllers/'));
```
but I can't get access to req.params in `config.verifyToken` function, the params not exist before mapRoutes, any idea how I can evaluate path params like /users/:ID?

**Comment by toksdotdev** [comment]
I'm currently working on a PR for this; I'll see if I can wrap up, and submit for review immediately.

Sorry for the delay @aichbauer & @joneldiablo

**Comment by toksdotdev** [comment]
I just added the feature; it's awaiting review. @aichbauer and @joneldiablo

**Comment by aichbauer** [comment]
@TNkemdilim I will review it, during this week or next week. Thank you for your contribution 👍

**Comment by joneldiablo** [comment]
hi @TNkemdilim @aichbauer yesterday I did a pull request to the TNkemdilim fork, to use a middleware for all routes

**Comment by alkanyunus** [comment]
@joneldiablo so we can't use it yet :/ waiting...

**Comment by joneldiablo** [comment]
@saxahan you can use the @TNkemdilim fork XD or wait for @aichbauer accept the pr
XD

**Comment by toksdotdev** [comment]
Just made necessary updates to the PR...

**Comment by aichbauer** [comment]
I'll review it tomorrow. if everything is okay i'll release a new version tomorrow.
