### ISSUE TITLE
Problem with routes

### ISSUE THREAD

**Issue by ianninirojas** [rudolfsonjunior/express-routes-mapper#23]
Hi! I'm triying run the project but I have this error
/express-rest-api-boilerplate/api/api.js:26
const mappedOpenRoutes = mapRoutes(config.publicRoutes, 'api/controllers/');
^

TypeError: mapRoutes is not a function

Thanks

**Comment by aichbauer** [comment]
Hey we are currently working on a fix. Thanks for the issue. Please downgrade to `1.0.2`.
