### ISSUE TITLE
controller as class: this is undefined!

### ISSUE THREAD

**Issue by joneldiablo** [rudolfsonjunior/express-routes-mapper#29]
using my controller as class the _this_ is undefined!!

**Comment by joneldiablo** [comment]
```
/**
 * @class UserController
 */
class UserController extends Controller {
  constructor() {
    super(User, ['firstname', 'lastname', 'socialSecurityNumber', 'birthdate', 'email']);
  }
....
}
/**
 * @class Controller
 */
class Controller {
  constructor(model, qcolumns) {
    this.model = model;
    this.qcolumns = qcolumns;
  }
  get(req, res) {
    let status = 200;
    let response = {
      success: true
    }
    let query = req.params.q || '';
   
    console.log(typeof this);
}
```

**Comment by aichbauer** [comment]
Could you please create a repository where you reproduce this issue?

Which version of `express-routes-mapper` are you using? 
Which `node` version are you using?
How does your `routes` file look like?

**Comment by joneldiablo** [comment]
"express-routes-mapper": "^1.0.4",
I think the problem comes from express, the solution was to bind the "this" in the constructor:
```
constructor(model, qcolumns) {
    this.model = model.query();
    this.qcolumns = qcolumns;
    //PATCH: _this_ is undefined using express and express-routes-mapper
    this.get = this.get.bind(this);
    this.set = this.set.bind(this);
    this.getByID = this.getByID.bind(this);
    this.update = this.update.bind(this);
    this.delete = this.delete.bind(this);
  }
```
![image](https://user-images.githubusercontent.com/13206502/47026412-fc81d980-d12a-11e8-99bc-1b1c775014c8.png)

![image](https://user-images.githubusercontent.com/13206502/47026949-24257180-d12c-11e8-8dfe-869ba55a32fd.png)

**Comment by aichbauer** [comment]
Alright, thanks for posting the solution 👍 

I will close this issue for now.

**Comment by joneldiablo** [comment]
#32
